import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteNavbar from '@/components/SiteNavbar'
import SiteHeader from '@/components/SiteHeader'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="he" dir="rtl">
<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
  <SiteHeader />
  {children}
</body>
    </html>
  )
}
